import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";

function TwoFactorSetup() {
  const navigate = useNavigate();
  const { t } = useTranslation();

  const [code, setCode] = useState(["", "", "", "", "", ""]);
  const [error, setError] = useState("");

  const handleChange = (value, index) => {
    if (!/^\d?$/.test(value)) {
      return;
    }

    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);

    if (value && index < code.length - 1) {
      document
        .getElementById(`two-factor-${index + 1}`)
        ?.focus();
    }

    setError("");
  };

  const handleKeyDown = (event, index) => {
    if (
      event.key === "Backspace" &&
      !code[index] &&
      index > 0
    ) {
      document
        .getElementById(`two-factor-${index - 1}`)
        ?.focus();
    }
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    const verificationCode = code.join("");

    if (verificationCode.length !== 6) {
      setError(t("twoFactor.invalidCode"));
      return;
    }

    /*
      BACKEND INTEGRATION WILL GO HERE.

      The backend will eventually verify the TOTP code
      generated by the user's authenticator application.

      For now, we simply show the frontend flow.
    */

    navigate("/auth/two-factor-enabled");
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] px-5 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-lg items-center justify-center">
        <div className="w-full">

          {/* Logo */}
          <div className="mb-8 flex justify-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#0EA5E9] shadow-md">
              <span className="text-2xl font-bold text-white">
                AT
              </span>
            </div>
          </div>

          {/* Header */}
          <div className="mb-8 text-center">
            <div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-full bg-[#E0F2FE]">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.8"
                className="h-7 w-7 text-[#0EA5E9]"
              >
                <rect
                  width="18"
                  height="11"
                  x="3"
                  y="10"
                  rx="2"
                />
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M7 10V7a5 5 0 0 1 10 0v3"
                />
              </svg>
            </div>

            <h1 className="text-3xl font-bold tracking-tight text-[#0F172A]">
              {t("twoFactor.title")}
            </h1>

            <p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#64748B]">
              {t("twoFactor.description")}
            </p>
          </div>

          {/* Main Card */}
          <div className="rounded-3xl border border-[#CBD5E1] bg-white p-6 shadow-sm sm:p-8">

            {/* Step 1 */}
            <div className="mb-8">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#0EA5E9] text-sm font-bold text-white">
                  1
                </div>

                <h2 className="text-base font-bold text-[#0F172A]">
                  {t("twoFactor.stepOneTitle")}
                </h2>
              </div>

              <p className="mb-5 text-sm leading-6 text-[#64748B]">
                {t("twoFactor.stepOneDescription")}
              </p>

              {/* QR Placeholder */}
              <div className="mx-auto flex h-48 w-48 items-center justify-center rounded-2xl border-2 border-dashed border-[#CBD5E1] bg-[#F8FAFC]">
                <div className="text-center">
                  <div className="mx-auto mb-3 flex h-20 w-20 items-center justify-center rounded-xl bg-[#E2E8F0]">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      className="h-10 w-10 text-[#64748B]"
                    >
                      <rect
                        width="5"
                        height="5"
                        x="3"
                        y="3"
                      />
                      <rect
                        width="5"
                        height="5"
                        x="16"
                        y="3"
                      />
                      <rect
                        width="5"
                        height="5"
                        x="3"
                        y="16"
                      />
                      <path d="M16 16h2v2h-2zM20 16h1v1h-1zM16 20h1v1h-1zM19 19h2v2h-2z" />
                    </svg>
                  </div>

                  <p className="text-xs font-medium text-[#64748B]">
                    {t("twoFactor.qrPlaceholder")}
                  </p>
                </div>
              </div>
            </div>

            {/* Divider */}
            <div className="mb-8 flex items-center gap-4">
              <div className="h-px flex-1 bg-[#CBD5E1]" />

              <span className="text-xs font-medium text-[#94A3B8]">
                {t("twoFactor.or")}
              </span>

              <div className="h-px flex-1 bg-[#CBD5E1]" />
            </div>

            {/* Manual Setup Key */}
            <div className="mb-8 rounded-2xl bg-[#F8FAFC] p-4">
              <p className="text-xs font-semibold text-[#64748B]">
                {t("twoFactor.manualKey")}
              </p>

              <div className="mt-3 rounded-xl border border-[#CBD5E1] bg-white px-4 py-3 text-center">
                <span className="break-all font-mono text-sm font-semibold tracking-wider text-[#0F172A]">
                  BACKEND_SETUP_KEY
                </span>
              </div>

              <p className="mt-2 text-xs leading-5 text-[#94A3B8]">
                {t("twoFactor.manualKeyDescription")}
              </p>
            </div>

            {/* Step 2 */}
            <div className="mb-7">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#0EA5E9] text-sm font-bold text-white">
                  2
                </div>

                <h2 className="text-base font-bold text-[#0F172A]">
                  {t("twoFactor.stepTwoTitle")}
                </h2>
              </div>

              <p className="mb-5 text-sm leading-6 text-[#64748B]">
                {t("twoFactor.stepTwoDescription")}
              </p>

              {/* OTP */}
              <div className="flex justify-center gap-2 sm:gap-3">
                {code.map((digit, index) => (
                  <input
                    key={index}
                    id={`two-factor-${index}`}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={digit}
                    onChange={(event) =>
                      handleChange(event.target.value, index)
                    }
                    onKeyDown={(event) =>
                      handleKeyDown(event, index)
                    }
                    className={`h-12 w-10 rounded-xl border bg-white text-center text-lg font-bold text-[#0F172A] outline-none transition focus:ring-4 sm:h-14 sm:w-12 ${
                      error
                        ? "border-[#DC2626] focus:border-[#DC2626] focus:ring-red-100"
                        : "border-[#CBD5E1] focus:border-[#0EA5E9] focus:ring-[#E0F2FE]"
                    }`}
                  />
                ))}
              </div>

              {error && (
                <p className="mt-3 text-center text-sm font-medium text-[#DC2626]">
                  {error}
                </p>
              )}
            </div>

            {/* Verify */}
            <button
              type="button"
              onClick={handleSubmit}
              className="w-full rounded-xl bg-[#0EA5E9] px-6 py-4 text-sm font-semibold text-white shadow-sm transition hover:bg-[#0284C7] focus:outline-none focus:ring-4 focus:ring-[#BAE6FD]"
            >
              {t("twoFactor.enableButton")}
            </button>

            {/* Cancel */}
            <button
              type="button"
              onClick={() => navigate("/auth/welcome")}
              className="mt-5 w-full text-sm font-semibold text-[#64748B] transition hover:text-[#0F172A]"
            >
              {t("common.back")}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TwoFactorSetup;